a = input('Digite algo:')
print('Seu tipo primitivo desse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabético? ', a.isalnum())
print('Esta em maiusculas? ', a.isupper())
print('Esta em Minusculas? ', a.islower())
print('Esta capitalizada?', a.istitle())
